=== z-Fng/DEV-tools/bucket/schema_jingyu9575.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "hashPattern": {
            "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
            "type": "string"
        },
        "hash": {
            "anyOf": [
                {
                    "$ref": "#/definitions/hashPattern"
                },
                {
                    "items": {
                        "$ref": "#/definitions/hashPattern"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "hashExtraction": {
            "additionalProperties": false,
            "properties": {
                "find": {
                    "format": "regex",
                    "type": "string",
                    "description": "Same as 'regex'"
                },
                "regex": {
                    "format": "regex",
                    "type": "string"
                },
                "jp": {
                    "pattern": "^\\$[.[].*$",
                    "type": "string",
                    "description": "Same as 'jsonpath'"
                },
                "jsonpath": {
                    "pattern": "^\\$[.[].*$",
                    "type": "string"
                },
                "xpath": {
                    "type": "string"
                },
                "mode": {
                    "enum": [
                        "download",
                        "extract",
                        "json",
                        "xpath",
                        "rdf",
                        "metalink",
                        "fosshub",
                        "sourceforge"
                    ]
                },
                "type": {
                    "enum": [
                        "md5",
                        "sha1",
                        "sha256",
                        "sha512"
                    ],
                    "description": "Deprecated, hash type is determined automatically"
                },
                "url": {
                    "anyOf": [
                        {
                            "format": "uri",
                            "type": "string"
                        },
                        {
                            "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                            "type": "string"
                        },
                        {
                            "pattern": "^.*(\\$url|\\$baseurl).*$",
                            "type": "string"
                        }
                    ]
                }
            },
            "type": "object"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "bin": {
                    "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
                },
                "checkver": {
                    "$ref": "#/definitions/checkver"
                },
                "env_add_path": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "env_set": {
                    "type": "object"
                },
                "extract_dir": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "hash": {
                    "$ref": "#/definitions/hash"
                },
                "installer": {
                    "$ref": "#/definitions/installer"
                },
                "msi": {
                    "$ref": "#/definitions/stringOrArrayOfStrings",
                    "description": "Deprecated"
                },
                "post_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "pre_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "shortcuts": {
                    "$ref": "#/definitions/shortcutsArray"
                },
                "uninstaller": {
                    "$ref": "#/definitions/uninstaller"
                },
                "url": {
                    "$ref": "#/definitions/uriOrArrayOfUris"
                }
            },
            "type": "object"
        },
        "arrayOfArrayOfStrings": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "shortcutsArray": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 2,
                "maxItems": 4,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "autoupdate": {
            "additionalProperties": false,
            "properties": {
                "architecture": {
                    "additionalProperties": false,
                    "properties": {
                        "32bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                }
                            },
                            "type": "object"
                        },
                        "64bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                },
                "extract_dir": {
                    "type": "string"
                },
                "hash": {
                    "$ref": "#/definitions/hashExtraction"
                },
                "note": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "url": {
                    "format": "uri",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "checkver": {
            "anyOf": [
                {
                    "format": "regex",
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "github": {
                            "format": "uri",
                            "type": "string"
                        },
                        "re": {
                            "format": "regex",
                            "type": "string",
                            "description": "Same as 'regex'"
                        },
                        "regex": {
                            "format": "regex",
                            "type": "string"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        },
                        "jp": {
                            "pattern": "^\\$[.[].*$",
                            "type": "string",
                            "description": "Same as 'jsonpath'"
                        },
                        "jsonpath": {
                            "pattern": "^\\$[.[].*$",
                            "type": "string"
                        },
                        "xpath": {
                            "type": "string"
                        },
                        "reverse": {
                            "description": "Reverse the order of regex matches",
                            "type": "boolean"
                        },
                        "replace": {
                            "description": "Allows rearrange the regexp matches",
                            "type": "string"
                        },
                        "useragent": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            ]
        },
        "installer": {
            "additionalProperties": false,
            "properties": {
                "_comment": {
                    "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
                    "type": "string"
                },
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "keep": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "stringOrArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "$ref": "#/definitions/stringOrArrayOfStrings"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "uninstaller": {
            "properties": {
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "oneOf": [
                {
                    "required": [
                        "file"
                    ]
                },
                {
                    "required": [
                        "script"
                    ]
                }
            ],
            "type": "object"
        },
        "uriOrArrayOfUris": {
            "anyOf": [
                {
                    "format": "uri",
                    "not": {
                        "pattern": "(\\$)"
                    },
                    "type": "string"
                },
                {
                    "items": {
                        "format": "uri",
                        "not": {
                            "pattern": "(\\$)"
                        },
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "licenseIdentifiers": {
            "type": "string",
            "description": "License identifier based on SPDX License List https://spdx.org/licenses/",
            "examples": [
                "Apache-2.0",
                "BSD-3-Clause",
                "Freeware",
                "GPL-2.0-only",
                "GPL-2.0-or-later",
                "GPL-3.0-only",
                "GPL-3.0-or-later",
                "ISC",
                "LGPL-2.0-only",
                "LGPL-2.0-or-later",
                "LGPL-2.1-only",
                "LGPL-2.1-or-later",
                "LGPL-3.0-only",
                "LGPL-3.0-or-later",
                "MIT",
                "MS-PL",
                "Proprietary",
                "Public Domain",
                "Shareware",
                "Unlicense"
            ]
        }
    },
    "properties": {
        "_comment": {
            "description": "Deprecated. Use ## instead.",
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "##": {
            "description": "A comment.",
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "32bit": {
                    "$ref": "#/definitions/architecture"
                },
                "64bit": {
                    "$ref": "#/definitions/architecture"
                }
            },
            "type": "object"
        },
        "autoupdate": {
            "$ref": "#/definitions/autoupdate"
        },
        "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "checkver": {
            "$ref": "#/definitions/checkver"
        },
        "cookie": {
            "description": "Undocumented: Found at https://github.com/se35710/scoop-java/search?l=JSON&q=cookie",
            "type": "object"
        },
        "depends": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "description": {
            "type": "string"
        },
        "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
            "type": "object"
        },
        "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "extract_to": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "hash": {
            "$ref": "#/definitions/hash"
        },
        "homepage": {
            "format": "uri",
            "type": "string"
        },
        "innosetup": {
            "description": "True if the installer InnoSetup based. Found in https://github.com/ScoopInstaller/Scoop/search?l=JSON&q=innosetup",
            "type": "boolean"
        },
        "installer": {
            "$ref": "#/definitions/installer"
        },
        "license": {
            "anyOf": [
                {
                    "$ref": "#/definitions/licenseIdentifiers"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "url": {
                            "format": "uri",
                            "type": "string"
                        },
                        "identifier": {
                            "$ref": "#/definitions/licenseIdentifiers"
                        }
                    },
                    "required": [
                        "identifier"
                    ],
                    "type": "object"
                }
            ]
        },
        "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
        },
        "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "psmodule": {
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
        },
        "suggest": {
            "additionalProperties": false,
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uninstaller": {
            "$ref": "#/definitions/uninstaller"
        },
        "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
        },
        "version": {
            "pattern": "^[\\w\\.\\-_]+$",
            "type": "string"
        }
    },
    "required": [
        "version"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
}

=== z-Fng/DEV-tools/bucket/phpstorm-rc-portable.json
{
  "architecture": {
    "32bit": {
      "shortcuts": [
        [
          "IDE\\bin\\phpstorm.exe",
          "JetBrains\\PhpStorm (Release Candidate)"
        ]
      ]
    },
    "64bit": {
      "shortcuts": [
        [
          "IDE\\bin\\phpstorm64.exe",
          "JetBrains\\PhpStorm (Release Candidate)"
        ]
      ]
    }
  },
  "autoupdate": {
    "hash": {
      "url": "$url.sha256"
    },
    "url": "https://download.jetbrains.com/webide/PhpStorm-$preReleaseVersion.exe#/cosi.7z"
  },
  "checkver": {
    "regex": "version\":\"(?<ver>[\\d.]+)\".*\"build\":\"(?<build>[\\d.]+)\"",
    "replace": "${ver}-${build}",
    "url": "https://data.services.jetbrains.com/products/releases?code=PS&latest=true&platform=zip&type=rc"
  },
  "description": "PhpStorm Release Candidate. Cross-Platform, Lightning-Smart IDE for PHP programming by JetBrains.",
  "extract_to": "IDE",
  "hash": [
    "2c90e51863e42296f935beec78895156018cdbe70a2bbb4ea18974f35a49329a",
    "2255673952a7909596b8783f6e913d2301f91f0def0275fcfbc6371b0ca021f8"
  ],
  "homepage": "https://www.jetbrains.com/phpstorm/",
  "installer": {
    "script": [
      "& \"$dir\\portable.ps1\" $dir $persist_dir",
      "Remove-Item \"$dir\\IDE\\`$*\", \"$dir\\portable.ps1\" -Force -Recurse"
    ]
  },
  "license": {
    "identifier": "Proprietary",
    "url": "https://www.jetbrains.com/store/license.html"
  },
  "persist": [
    "IDE\\bin\\idea.properties",
    "profile"
  ],
  "url": [
    "https://download.jetbrains.com/webide/PhpStorm-231.8109.149.exe#/cosi.7z",
    "https://ghproxy.com/https://raw.githubusercontent.com/shovel-org/Windows-JetBrains-Bucket/main/scripts/portable.ps1"
  ],
  "version": "2023.1-231.8109.149"
}

=== z-Fng/DEV-tools/bucket/oh-my-posh3.json
{
  "architecture": {
    "64bit": {
      "hash": "bc0bb6992ba5c3c09d3df623a2143a80d0dade156be99fe23fe40cc48ab797df",
      "url": "https://ghproxy.com/https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v5.14.1/posh-windows-wsl-amd64.7z"
    }
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://ghproxy.com/https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v$version/posh-windows-wsl-amd64.7z"
      }
    },
    "hash": {
      "regex": "$sha256",
      "url": "$url.sha256"
    }
  },
  "bin": "bin\\oh-my-posh.exe",
  "checkver": {
    "github": "https://github.com/JanDeDobbeleer/oh-my-posh"
  },
  "description": "A prompt theme engine for any shell",
  "homepage": "https://ohmyposh.dev",
  "license": "GPL-3.0-only",
  "notes": "Refer to 'https://ohmyposh.dev/docs/windows#replace-your-existing-prompt' for shell specific configurations.",
  "persist": "themes",
  "version": "5.14.1"
}

=== z-Fng/DEV-tools/bucket/hiddify-next.json
{
    "version": "2.5.7",
    "description": "Multi-platform auto-proxy client, supporting Sing-box, X-ray, TUIC, Hysteria, Reality, Trojan, SSH etc. It’s an open-source, secure and ad-free.",
    "homepage": "https://hiddify.com/",
    "license": {
        "identifier": "CC-BY-NC-SA-4.0",
        "url": "https://github.com/hiddify/hiddify-app/blob/main/LICENSE.md"
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/hiddify/hiddify-app/releases/download/v2.5.7/Hiddify-Windows-Portable-x64.zip",
            "hash": "dbb4ae2d70395c20ae3de86afd047f0be9ffb20d42be5a104e332f6469cdb6d7"
        }
    },
    "extract_dir": "HiddifyNext-portable",
    "installer": {
        "script": [
            "ensure \"$persist_dir\" | Out-Null",
            "New-Item \"$env:APPDATA\\Hiddify\" -ItemType Junction -Target \"$persist_dir\" | Out-Null"
        ]
    },
    "uninstaller": {
        "script": "Remove-Item \"$env:APPDATA\\Hiddify\" -Recurse -Force -ErrorAction 'SilentlyContinue'"
    },
    "shortcuts": [
        [
            "HiddifyNext.exe",
            "HiddifyNext"
        ]
    ],
    "checkver": {
        "url": "https://api.github.com/repos/hiddify/hiddify-app/releases",
        "jsonpath": "$[0].assets[*].browser_download_url",
        "regex": "/releases/download/v([\\w.]+)/(?<file>(?:hiddify|Hiddify)-(?:windows|Windows)-(?:portable|Portable)-x64\\.zip)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/hiddify/hiddify-app/releases/download/v$version/$matchFile"
            }
        }
    }
}

=== z-Fng/DEV-tools/bucket/EverythingToolbar_kkzzhizhou.json
{
    "homepage": "https://github.com/srwi/EverythingToolbar",
    "description": "Everything integration for the Windows taskbar",
    "version": "1.5.5",
    "url": "https://github.com/srwi/EverythingToolbar/releases/download/1.5.5/EverythingToolbar-1.5.5.msi#/setup.msi_",
    "hash": "ca617b34a6ca89b4410613112265eeabd5726c62291601836003bbb2f2078803",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/srwi/EverythingToolbar/releases/download/$version/EverythingToolbar-$version.msi#/setup.msi_"
    },
    "installer": {
        "script": "Start-Process -Wait msiexec \"/i `\"$dir\\setup.msi_`\"/norestart /qn INSTALLFOLDER=`\"$dir`\"\" -Verb RunAs"
    },
    "uninstaller": {
        "script": "Start-Process -Wait msiexec \"/x `\"$dir\\setup.msi_`\" /qn /norestart\" -Verb RunAs"
    }
}

=== z-Fng/DEV-tools/bucket/dotnet-script_batkiz.json
{
    "homepage": "https://github.com/dotnet-script/dotnet-script",
    "description": "Run C# scripts from the .NET CLI.",
    "license": "MIT",
    "version": "2.0.0",
    "suggest": {
        "dotnet core SDK": "dotnet-sdk"
    },
    "url": "https://github.com/dotnet-script/dotnet-script/releases/download/2.0.0/dotnet-script.2.0.0.zip",
    "hash": "ad2ee311952c407906e3436589e1e5f6d666941959feeeab24913c551d404066",
    "extract_dir": "dotnet-script",
    "bin": "dotnet-script.cmd",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/dotnet-script/dotnet-script/releases/download/$version/dotnet-script.$version.zip"
    }
}

=== z-Fng/DEV-tools/bucket/wasm-pack.json
{
    "version": "0.13.1",
    "description": "Your favorite Rust → Wasm workflow tool!",
    "homepage": "https://rustwasm.github.io/wasm-pack/",
    "license": "Apache-2.0|MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/wasm-bindgen/wasm-pack/releases/download/v0.13.1/wasm-pack-v0.13.1-x86_64-pc-windows-msvc.tar.gz",
            "hash": "4fd5375c2f85bae92c3e8fb14ad0d27b8fb92e85f4397064d9e66a94a79d6fae",
            "extract_dir": "wasm-pack-v0.13.1-x86_64-pc-windows-msvc"
        }
    },
    "bin": "wasm-pack.exe",
    "checkver": {
        "github": "https://github.com/wasm-bindgen/wasm-pack"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/wasm-bindgen/wasm-pack/releases/download/v$version/wasm-pack-v$version-x86_64-pc-windows-msvc.tar.gz",
                "extract_dir": "wasm-pack-v$version-x86_64-pc-windows-msvc"
            }
        }
    }
}

=== z-Fng/DEV-tools/bucket/scoop-completion_chawyehsu.json
{
    "homepage": "https://github.com/Moeologist/scoop-completion/",
    "description": "Scoop tab completion, work with powershell",
    "version": "nightly",
    "license": "MIT",
    "url": "https://github.com/Moeologist/scoop-completion/archive/master.zip",
    "extract_dir": "scoop-completion-master/src",
    "psmodule": {
        "name": "scoop-completion"
    },
    "post_install": "Import-Module $env:USERPROFILE\\scoop\\modules\\scoop-completion",
    "notes": [
        "To enable completion autoload, you need to add scoop-completion module to PowerShell $PROFILE by running:",
        "Add-Content -Path $Profile -Value \"`nImport-Module $env:USERPROFILE\\scoop\\modules\\scoop-completion\""
    ]
}

=== z-Fng/DEV-tools/bucket/steampp.json
{
    "version": "3.0.0-rc.16",
    "description": "Steam++ is a toolbox with lots of Steam tools",
    "homepage": "https://steampp.net/",
    "license": "GPL-3.0-only",
    "url": "https://github.com/BeyondDimension/SteamTools/releases/download/3.0.0-rc.16/Steam%2B%2B_v3.0.0-rc.16_win_x64.7z",
    "hash": "36eb952eec538af7e2c4d5b8d7bed8e9232e7349f054f094221e4486f0dbe893",
    "shortcuts": [
        [
            "Steam++.exe",
            "Steam++"
        ]
    ],
    "persist": "AppData",
    "checkver": {
        "url": "https://api.github.com/repos/BeyondDimension/SteamTools/releases",
        "regex": "v([\\w.-]+)_win_x64.7z"
    },
    "autoupdate": {
        "url": "https://github.com/BeyondDimension/SteamTools/releases/download/$version/Steam%2B%2B_v$version_win_x64.7z",
        "hash": {
            "url": "https://api.github.com/repos/BeyondDimension/SteamTools/releases",
            "regex": "$version_win_x64.7z.*?$sha256"
        }
    }
}
