=== z-Fng/DEV-tools/bucket/schema_jingyu9575.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "hashPattern": {
            "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
            "type": "string"
        },
        "hash": {
            "anyOf": [
                {
                    "$ref": "#/definitions/hashPattern"
                },
                {
                    "items": {
                        "$ref": "#/definitions/hashPattern"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "hashExtraction": {
            "additionalProperties": false,
            "properties": {
                "find": {
                    "format": "regex",
                    "type": "string",
                    "description": "Same as 'regex'"
                },
                "regex": {
                    "format": "regex",
                    "type": "string"
                },
                "jp": {
                    "pattern": "^\\$[.[].*$",
                    "type": "string",
                    "description": "Same as 'jsonpath'"
                },
                "jsonpath": {
                    "pattern": "^\\$[.[].*$",
                    "type": "string"
                },
                "xpath": {
                    "type": "string"
                },
                "mode": {
                    "enum": [
                        "download",
                        "extract",
                        "json",
                        "xpath",
                        "rdf",
                        "metalink",
                        "fosshub",
                        "sourceforge"
                    ]
                },
                "type": {
                    "enum": [
                        "md5",
                        "sha1",
                        "sha256",
                        "sha512"
                    ],
                    "description": "Deprecated, hash type is determined automatically"
                },
                "url": {
                    "anyOf": [
                        {
                            "format": "uri",
                            "type": "string"
                        },
                        {
                            "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                            "type": "string"
                        },
                        {
                            "pattern": "^.*(\\$url|\\$baseurl).*$",
                            "type": "string"
                        }
                    ]
                }
            },
            "type": "object"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "bin": {
                    "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
                },
                "checkver": {
                    "$ref": "#/definitions/checkver"
                },
                "env_add_path": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "env_set": {
                    "type": "object"
                },
                "extract_dir": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "hash": {
                    "$ref": "#/definitions/hash"
                },
                "installer": {
                    "$ref": "#/definitions/installer"
                },
                "msi": {
                    "$ref": "#/definitions/stringOrArrayOfStrings",
                    "description": "Deprecated"
                },
                "post_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "pre_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "shortcuts": {
                    "$ref": "#/definitions/shortcutsArray"
                },
                "uninstaller": {
                    "$ref": "#/definitions/uninstaller"
                },
                "url": {
                    "$ref": "#/definitions/uriOrArrayOfUris"
                }
            },
            "type": "object"
        },
        "arrayOfArrayOfStrings": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "shortcutsArray": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 2,
                "maxItems": 4,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "autoupdate": {
            "additionalProperties": false,
            "properties": {
                "architecture": {
                    "additionalProperties": false,
                    "properties": {
                        "32bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                }
                            },
                            "type": "object"
                        },
                        "64bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                },
                "extract_dir": {
                    "type": "string"
                },
                "hash": {
                    "$ref": "#/definitions/hashExtraction"
                },
                "note": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "url": {
                    "format": "uri",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "checkver": {
            "anyOf": [
                {
                    "format": "regex",
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "github": {
                            "format": "uri",
                            "type": "string"
                        },
                        "re": {
                            "format": "regex",
                            "type": "string",
                            "description": "Same as 'regex'"
                        },
                        "regex": {
                            "format": "regex",
                            "type": "string"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        },
                        "jp": {
                            "pattern": "^\\$[.[].*$",
                            "type": "string",
                            "description": "Same as 'jsonpath'"
                        },
                        "jsonpath": {
                            "pattern": "^\\$[.[].*$",
                            "type": "string"
                        },
                        "xpath": {
                            "type": "string"
                        },
                        "reverse": {
                            "description": "Reverse the order of regex matches",
                            "type": "boolean"
                        },
                        "replace": {
                            "description": "Allows rearrange the regexp matches",
                            "type": "string"
                        },
                        "useragent": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            ]
        },
        "installer": {
            "additionalProperties": false,
            "properties": {
                "_comment": {
                    "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
                    "type": "string"
                },
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "keep": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "stringOrArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "$ref": "#/definitions/stringOrArrayOfStrings"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "uninstaller": {
            "properties": {
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "oneOf": [
                {
                    "required": [
                        "file"
                    ]
                },
                {
                    "required": [
                        "script"
                    ]
                }
            ],
            "type": "object"
        },
        "uriOrArrayOfUris": {
            "anyOf": [
                {
                    "format": "uri",
                    "not": {
                        "pattern": "(\\$)"
                    },
                    "type": "string"
                },
                {
                    "items": {
                        "format": "uri",
                        "not": {
                            "pattern": "(\\$)"
                        },
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "licenseIdentifiers": {
            "type": "string",
            "description": "License identifier based on SPDX License List https://spdx.org/licenses/",
            "examples": [
                "Apache-2.0",
                "BSD-3-Clause",
                "Freeware",
                "GPL-2.0-only",
                "GPL-2.0-or-later",
                "GPL-3.0-only",
                "GPL-3.0-or-later",
                "ISC",
                "LGPL-2.0-only",
                "LGPL-2.0-or-later",
                "LGPL-2.1-only",
                "LGPL-2.1-or-later",
                "LGPL-3.0-only",
                "LGPL-3.0-or-later",
                "MIT",
                "MS-PL",
                "Proprietary",
                "Public Domain",
                "Shareware",
                "Unlicense"
            ]
        }
    },
    "properties": {
        "_comment": {
            "description": "Deprecated. Use ## instead.",
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "##": {
            "description": "A comment.",
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "32bit": {
                    "$ref": "#/definitions/architecture"
                },
                "64bit": {
                    "$ref": "#/definitions/architecture"
                }
            },
            "type": "object"
        },
        "autoupdate": {
            "$ref": "#/definitions/autoupdate"
        },
        "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "checkver": {
            "$ref": "#/definitions/checkver"
        },
        "cookie": {
            "description": "Undocumented: Found at https://github.com/se35710/scoop-java/search?l=JSON&q=cookie",
            "type": "object"
        },
        "depends": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "description": {
            "type": "string"
        },
        "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
            "type": "object"
        },
        "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "extract_to": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "hash": {
            "$ref": "#/definitions/hash"
        },
        "homepage": {
            "format": "uri",
            "type": "string"
        },
        "innosetup": {
            "description": "True if the installer InnoSetup based. Found in https://github.com/ScoopInstaller/Scoop/search?l=JSON&q=innosetup",
            "type": "boolean"
        },
        "installer": {
            "$ref": "#/definitions/installer"
        },
        "license": {
            "anyOf": [
                {
                    "$ref": "#/definitions/licenseIdentifiers"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "url": {
                            "format": "uri",
                            "type": "string"
                        },
                        "identifier": {
                            "$ref": "#/definitions/licenseIdentifiers"
                        }
                    },
                    "required": [
                        "identifier"
                    ],
                    "type": "object"
                }
            ]
        },
        "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
        },
        "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "psmodule": {
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
        },
        "suggest": {
            "additionalProperties": false,
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uninstaller": {
            "$ref": "#/definitions/uninstaller"
        },
        "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
        },
        "version": {
            "pattern": "^[\\w\\.\\-_]+$",
            "type": "string"
        }
    },
    "required": [
        "version"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
}

=== z-Fng/DEV-tools/bucket/windows-defender-control.json
{
    "version": "2",
    "description": "Manage Windows Defender in a few clicks (Windows 10/11).",
    "homepage": "https://github.com/yeulette/windows-defender-control",
    "license": "Unknown",
    "architecture": {
        "64bit": {
            "url": "https://github.com/yeulette/windows-defender-control/releases/download/WDC/WDC.bat",
            "hash": "8d10ab6532e1283811b4796938d025f4dd8dd6f5c3858c25c3d58e62225724bc"
        }
    },
    "shortcuts": [
        [
            "WDC.bat",
            "windows-defender-control"
        ]
    ],
    "checkver": {
        "url": "https://github.com/yeulette/windows-defender-control/releases",
        "regex": "v([\\d.]+)"
    },
    "autoupdate": {
        "url": "https://github.com/yeulette/windows-defender-control/releases/download/WDC/WDC.bat",
        "hash": {
            "mode": "download"
        }
    }
}

=== z-Fng/DEV-tools/bucket/wazero.json
{
    "version": "1.11.0",
    "description": "An zero dependency WebAssembly runtime for Go developers.",
    "homepage": "https://wazero.io/",
    "license": "Apache-2.0",
    "architecture": {
        "64bit": {
            "url": "https://github.com/wazero/wazero/releases/download/v1.11.0/wazero_1.11.0_windows_amd64.zip",
            "hash": "aefcf54798ac15ef138e7db3a595cc590314aea547f5a65dfb8f86853655d40e"
        }
    },
    "bin": "wazero.exe",
    "checkver": {
        "github": "https://github.com/wazero/wazero"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/wazero/wazero/releases/download/v$version/wazero_$version_windows_amd64.zip"
            }
        },
        "hash": {
            "url": "$baseurl/wazero_$version_checksums.txt"
        }
    }
}

=== z-Fng/DEV-tools/bucket/pritunl-client.json
{
    "version": "1.3.4392.66",
    "description": "OpenVPN Client",
    "homepage": "https://client.pritunl.com",
    "license": {
        "identifier": "Freeware",
        "url": "https://github.com/pritunl/pritunl-client/blob/master/LICENSE"
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/pritunl/pritunl-client/releases/download/1.3.4392.66/Pritunl.exe#/dl.exe",
            "hash": "31f491e42f72cdf440e3b7e12780b507842e12ea5faa5456da459e6387201bf9"
        }
    },
    "innosetup": true,
    "pre_install": "if (-not (is_admin)) { error 'This package requires admin privileges to install'; break }",
    "post_install": "Invoke-ExternalCommand \"$dir\\post_install.exe\" -RunAs | Out-Null",
    "uninstaller": {
        "script": [
            "if (-not (is_admin)) { error 'This package requires admin privileges to uninstall'; break }",
            "Invoke-ExternalCommand \"$dir\\pre_uninstall.exe\" -RunAs | Out-Null",
            "Remove-Item 'C:\\ProgramData\\Pritunl' -Recurse -Force"
        ]
    },
    "bin": [
        [
            "pritunl.exe",
            "pritunl",
            "--no-main"
        ]
    ],
    "shortcuts": [
        [
            "pritunl.exe",
            "Pritunl"
        ]
    ],
    "checkver": "([\\d.]+)/Pritunl.exe",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/pritunl/pritunl-client/releases/download/$version/Pritunl.exe#/dl.exe",
                "hash": {
                    "url": "https://raw.githubusercontent.com/pritunl/pritunl-client/master/SHA256",
                    "regex": "$version[\\r\\n]+$sha256.*?$basename"
                }
            }
        }
    }
}

=== z-Fng/DEV-tools/bucket/roboto.json
{
    "homepage": "https://github.com/googlefonts/roboto-2",
    "version": "2.138",
    "description": "The Roboto family of fonts. (hrbrthemes)",
    "license": "Apache-2.0",
    "url": "https://github.com/googlefonts/roboto-2/releases/download/v2.138/roboto-unhinted.zip",
    "hash": "70f64c718510a601fbcf752aafe644314dacaeb85474dc689c89787c4a72a728",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/googlefonts/roboto-2/releases/download/v$version/roboto-unhinted.zip"
    }
}

=== z-Fng/DEV-tools/bucket/rare_Small-Ku.json
{
  "version": "1.10.11",
  "description": "A frontend for legendary, the open source Epic Games Launcher alternative.",
  "homepage": "https://github.com/RareDevs/Rare",
  "license": "GPL-3.0-only",
  "architecture": {
    "64bit": {
      "url": "https://github.com/RareDevs/Rare/releases/download/1.10.11/Rare-Windows-1.10.11.zip",
      "hash": "e917b0b8154ea57e0ed37270287f9d18c4df5fbc31bac9112d99e48148cad95e"
    }
  },
  "shortcuts": [
    [
      "Rare.exe",
      "Rare"
    ]
  ],
  "notes": "Rare is NOT portable.",
  "checkver": "github",
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://github.com/RareDevs/Rare/releases/download/$version/Rare-Windows-$version.zip"
      }
    }
  }
}

=== z-Fng/DEV-tools/bucket/beatsaber-modassistant.json
{
    "version": "1.1.35",
    "description": "Simple Beat Saber Mod Installer",
    "homepage": "https://github.com/bsmg/ModAssistant",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/bsmg/ModAssistant/releases/download/v1.1.35/ModAssistant.exe",
            "hash": "3aba35dab86c8ce368ebf266c232af096e5b5509cb5f28e11c79efc839f54cc7"
        }
    },
    "shortcuts": [
        [
            "ModAssistant.exe",
            "Beat Saber Mod Assistant"
        ]
    ],
    "checkver": {
        "github": "https://github.com/bsmg/ModAssistant"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/bsmg/ModAssistant/releases/download/v$version/ModAssistant.exe"
            }
        }
    }
}

=== z-Fng/DEV-tools/bucket/plain-craft-launcher.json
{
    "version": "2.12.2",
    "description": "新一代 Minecraft / 我的世界 启动器",
    "homepage": "https://github.com/Meloong-Git/PCL",
    "license": {
        "identifier": "Freeware",
        "url": "https://shimo.im/docs/rGrd8pY8xWkt6ryW/read"
    },
    "url": "https://github.com/Meloong-Git/PCL/raw/main/%E6%9C%80%E6%96%B0%E6%AD%A3%E5%BC%8F%E7%89%88.zip",
    "hash": "2bbb47a4c3d2a37b78731ec72f038c4bc7ce4e62fdb3f1302a6de593616bcd47",
    "pre_install": [
        "ensure \"$persist_dir\\PCL\" | Out-Null",
        "ensure \"$persist_dir\\.minecraft\" | Out-Null",
        "$conf = \"$persist_dir\\PCL\\Setup.ini\"",
        "if (!(Test-Path \"$conf\")) {",
        "    $content = \"LaunchFolderSelect:$persist_dir\\.minecraft\\\"",
        "    Add-Content \"$conf\" \"$content\"",
        "}"
    ],
    "persist": [
        "PCL",
        ".minecraft"
    ],
    "shortcuts": [
        [
            "Plain Craft Launcher 2.exe",
            "Plain Craft Launcher"
        ]
    ],
    "autoupdate": {
        "url": "https://github.com/Meloong-Git/PCL/raw/main/%E6%9C%80%E6%96%B0%E6%AD%A3%E5%BC%8F%E7%89%88.zip"
    },
    "checkver": "github"
}

=== z-Fng/DEV-tools/bucket/borderless-gaming.json
{
    "version": "9.5.6",
    "description": "Play your favorite games in a borderless window; no more time consuming alt-tabs",
    "homepage": "https://github.com/andrewmd5/Borderless-Gaming",
    "license": "GPL-2.0",
    "url": "https://github.com/andrewmd5/Borderless-Gaming/releases/download/9.5.6/BorderlessGaming9.5.6_admin_setup.exe",
    "hash": "250d2d883cb9f5a05a60be5b74191ca357489686a979cf7832fcb4c5f0522eda",
    "innosetup": true,
    "shortcuts": [
        [
            "BorderlessGaming.exe",
            "Borderless Gaming"
        ]
    ],
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/andrewmd5/Borderless-Gaming/releases/download/$version/BorderlessGaming$version_admin_setup.exe"
    }
}
