=== z-Fng/DEV-tools/bucket/schema_jingyu9575.json
{
    "$id": "http://scoop.sh/draft/schema#",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "hashPattern": {
            "pattern": "^([a-fA-F0-9]{64}|(sha1|sha256|sha512|md5):([a-fA-F0-9]{32}|[a-fA-F0-9]{40}|[a-fA-F0-9]{64}|[a-fA-F0-9]{128}))$",
            "type": "string"
        },
        "hash": {
            "anyOf": [
                {
                    "$ref": "#/definitions/hashPattern"
                },
                {
                    "items": {
                        "$ref": "#/definitions/hashPattern"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "hashExtraction": {
            "additionalProperties": false,
            "properties": {
                "find": {
                    "format": "regex",
                    "type": "string",
                    "description": "Same as 'regex'"
                },
                "regex": {
                    "format": "regex",
                    "type": "string"
                },
                "jp": {
                    "pattern": "^\\$[.[].*$",
                    "type": "string",
                    "description": "Same as 'jsonpath'"
                },
                "jsonpath": {
                    "pattern": "^\\$[.[].*$",
                    "type": "string"
                },
                "xpath": {
                    "type": "string"
                },
                "mode": {
                    "enum": [
                        "download",
                        "extract",
                        "json",
                        "xpath",
                        "rdf",
                        "metalink",
                        "fosshub",
                        "sourceforge"
                    ]
                },
                "type": {
                    "enum": [
                        "md5",
                        "sha1",
                        "sha256",
                        "sha512"
                    ],
                    "description": "Deprecated, hash type is determined automatically"
                },
                "url": {
                    "anyOf": [
                        {
                            "format": "uri",
                            "type": "string"
                        },
                        {
                            "pattern": "^(\\$url|\\$baseurl).[\\w\\d]+$",
                            "type": "string"
                        },
                        {
                            "pattern": "^.*(\\$url|\\$baseurl).*$",
                            "type": "string"
                        }
                    ]
                }
            },
            "type": "object"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "bin": {
                    "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
                },
                "checkver": {
                    "$ref": "#/definitions/checkver"
                },
                "env_add_path": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "env_set": {
                    "type": "object"
                },
                "extract_dir": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "hash": {
                    "$ref": "#/definitions/hash"
                },
                "installer": {
                    "$ref": "#/definitions/installer"
                },
                "msi": {
                    "$ref": "#/definitions/stringOrArrayOfStrings",
                    "description": "Deprecated"
                },
                "post_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "pre_install": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "shortcuts": {
                    "$ref": "#/definitions/shortcutsArray"
                },
                "uninstaller": {
                    "$ref": "#/definitions/uninstaller"
                },
                "url": {
                    "$ref": "#/definitions/uriOrArrayOfUris"
                }
            },
            "type": "object"
        },
        "arrayOfArrayOfStrings": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "shortcutsArray": {
            "items": {
                "items": {
                    "type": "string"
                },
                "minItems": 2,
                "maxItems": 4,
                "type": "array"
            },
            "minItems": 1,
            "type": "array"
        },
        "autoupdate": {
            "additionalProperties": false,
            "properties": {
                "architecture": {
                    "additionalProperties": false,
                    "properties": {
                        "32bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                }
                            },
                            "type": "object"
                        },
                        "64bit": {
                            "additionalProperties": false,
                            "properties": {
                                "extract_dir": {
                                    "type": "string"
                                },
                                "url": {
                                    "format": "uri",
                                    "type": "string"
                                },
                                "hash": {
                                    "$ref": "#/definitions/hashExtraction"
                                }
                            },
                            "type": "object"
                        }
                    },
                    "type": "object"
                },
                "extract_dir": {
                    "type": "string"
                },
                "hash": {
                    "$ref": "#/definitions/hashExtraction"
                },
                "note": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "url": {
                    "format": "uri",
                    "type": "string"
                }
            },
            "type": "object"
        },
        "checkver": {
            "anyOf": [
                {
                    "format": "regex",
                    "type": "string"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "github": {
                            "format": "uri",
                            "type": "string"
                        },
                        "re": {
                            "format": "regex",
                            "type": "string",
                            "description": "Same as 'regex'"
                        },
                        "regex": {
                            "format": "regex",
                            "type": "string"
                        },
                        "url": {
                            "format": "uri",
                            "type": "string"
                        },
                        "jp": {
                            "pattern": "^\\$[.[].*$",
                            "type": "string",
                            "description": "Same as 'jsonpath'"
                        },
                        "jsonpath": {
                            "pattern": "^\\$[.[].*$",
                            "type": "string"
                        },
                        "xpath": {
                            "type": "string"
                        },
                        "reverse": {
                            "description": "Reverse the order of regex matches",
                            "type": "boolean"
                        },
                        "replace": {
                            "description": "Allows rearrange the regexp matches",
                            "type": "string"
                        },
                        "useragent": {
                            "type": "string"
                        }
                    },
                    "type": "object"
                }
            ]
        },
        "installer": {
            "additionalProperties": false,
            "properties": {
                "_comment": {
                    "description": "Undocumented: only used in scoop-extras/oraclejdk* and scoop-extras/appengine-go",
                    "type": "string"
                },
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "keep": {
                    "type": "boolean"
                }
            },
            "type": "object"
        },
        "stringOrArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "stringOrArrayOfStringsOrAnArrayOfArrayOfStrings": {
            "anyOf": [
                {
                    "type": "string"
                },
                {
                    "items": {
                        "$ref": "#/definitions/stringOrArrayOfStrings"
                    },
                    "minItems": 1,
                    "type": "array"
                }
            ]
        },
        "uninstaller": {
            "properties": {
                "args": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                },
                "file": {
                    "type": "string"
                },
                "script": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "oneOf": [
                {
                    "required": [
                        "file"
                    ]
                },
                {
                    "required": [
                        "script"
                    ]
                }
            ],
            "type": "object"
        },
        "uriOrArrayOfUris": {
            "anyOf": [
                {
                    "format": "uri",
                    "not": {
                        "pattern": "(\\$)"
                    },
                    "type": "string"
                },
                {
                    "items": {
                        "format": "uri",
                        "not": {
                            "pattern": "(\\$)"
                        },
                        "type": "string"
                    },
                    "minItems": 1,
                    "type": "array",
                    "uniqueItems": true
                }
            ]
        },
        "licenseIdentifiers": {
            "type": "string",
            "description": "License identifier based on SPDX License List https://spdx.org/licenses/",
            "examples": [
                "Apache-2.0",
                "BSD-3-Clause",
                "Freeware",
                "GPL-2.0-only",
                "GPL-2.0-or-later",
                "GPL-3.0-only",
                "GPL-3.0-or-later",
                "ISC",
                "LGPL-2.0-only",
                "LGPL-2.0-or-later",
                "LGPL-2.1-only",
                "LGPL-2.1-or-later",
                "LGPL-3.0-only",
                "LGPL-3.0-or-later",
                "MIT",
                "MS-PL",
                "Proprietary",
                "Public Domain",
                "Shareware",
                "Unlicense"
            ]
        }
    },
    "properties": {
        "_comment": {
            "description": "Deprecated. Use ## instead.",
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "##": {
            "description": "A comment.",
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "architecture": {
            "additionalProperties": false,
            "properties": {
                "32bit": {
                    "$ref": "#/definitions/architecture"
                },
                "64bit": {
                    "$ref": "#/definitions/architecture"
                }
            },
            "type": "object"
        },
        "autoupdate": {
            "$ref": "#/definitions/autoupdate"
        },
        "bin": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "persist": {
            "$ref": "#/definitions/stringOrArrayOfStringsOrAnArrayOfArrayOfStrings"
        },
        "checkver": {
            "$ref": "#/definitions/checkver"
        },
        "cookie": {
            "description": "Undocumented: Found at https://github.com/se35710/scoop-java/search?l=JSON&q=cookie",
            "type": "object"
        },
        "depends": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "description": {
            "type": "string"
        },
        "env_add_path": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "env_set": {
            "type": "object"
        },
        "extract_dir": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "extract_to": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "hash": {
            "$ref": "#/definitions/hash"
        },
        "homepage": {
            "format": "uri",
            "type": "string"
        },
        "innosetup": {
            "description": "True if the installer InnoSetup based. Found in https://github.com/ScoopInstaller/Scoop/search?l=JSON&q=innosetup",
            "type": "boolean"
        },
        "installer": {
            "$ref": "#/definitions/installer"
        },
        "license": {
            "anyOf": [
                {
                    "$ref": "#/definitions/licenseIdentifiers"
                },
                {
                    "additionalProperties": false,
                    "properties": {
                        "url": {
                            "format": "uri",
                            "type": "string"
                        },
                        "identifier": {
                            "$ref": "#/definitions/licenseIdentifiers"
                        }
                    },
                    "required": [
                        "identifier"
                    ],
                    "type": "object"
                }
            ]
        },
        "msi": {
            "$ref": "#/definitions/stringOrArrayOfStrings",
            "description": "Deprecated"
        },
        "notes": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "post_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "pre_install": {
            "$ref": "#/definitions/stringOrArrayOfStrings"
        },
        "psmodule": {
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "shortcuts": {
            "$ref": "#/definitions/shortcutsArray"
        },
        "suggest": {
            "additionalProperties": false,
            "patternProperties": {
                "^(.*)$": {
                    "$ref": "#/definitions/stringOrArrayOfStrings"
                }
            },
            "type": "object"
        },
        "uninstaller": {
            "$ref": "#/definitions/uninstaller"
        },
        "url": {
            "$ref": "#/definitions/uriOrArrayOfUris"
        },
        "version": {
            "pattern": "^[\\w\\.\\-_]+$",
            "type": "string"
        }
    },
    "required": [
        "version"
    ],
    "title": "scoop app manifest schema",
    "type": "object"
}

=== z-Fng/DEV-tools/bucket/SQL-Studio.json
{
    "version": "0.1.46",
    "description": "Single binary, single command SQLite database explorer.",
    "homepage": "https://sqlite-studio.frectonz.io/",
    "license": "MIT",
    "url": "https://github.com/frectonz/sql-studio/releases/download/0.1.46/sql-studio-x86_64-pc-windows-msvc.zip",
    "hash": "239ff9b724f20e9227fa1bba39ebc818c2ea8d3388008f9c42b19fb5615b1461",
    "bin": "sql-studio.exe",
    "checkver": {
        "github": "https://github.com/frectonz/sql-studio/"
    },
    "autoupdate": {
        "url": "https://github.com/frectonz/sql-studio/releases/download/$version/sql-studio-x86_64-pc-windows-msvc.zip",
        "hash": {
            "url": "https://github.com/frectonz/sql-studio/releases/download/$version/sql-studio-x86_64-pc-windows-msvc.zip.sha256"
        }
    }
}

=== z-Fng/DEV-tools/bucket/jardiff.json
{
  "version": "1.7.0",
  "description": "A tool for comparing JAR files, including Scala pickled signatures and method code.",
  "homepage": "https://github.com/lightbend-labs/jardiff",
  "license": "Apache-2.0",
  "url": "https://ghproxy.com/https://github.com/lightbend-labs/jardiff/releases/download/v1.7.0/jardiff.jar",
  "hash": "564793f9d64f2cf304c49d63224e2aee30a2cd1f3e7ea580b79030278ff182c9",
  "bin": "jardiff.jar",
  "suggest": {
    "JDK": [
      "java/oraclejdk",
      "java/openjdk",
      "java/adoptopenjdk-hotspot",
      "java/zulu"
    ]
  },
  "checkver": "github",
  "autoupdate": {
    "url": "https://ghproxy.com/https://github.com/lightbend-labs/jardiff/releases/download/v$version/jardiff.jar"
  }
}

=== z-Fng/DEV-tools/bucket/runcat_hoilc.json
{
  "version": "2.0",
  "description": "https://github.com/Kyome22/RunCat365",
  "homepage": "https://github.com/Kyome22/RunCat365",
  "license": "Apache-2.0",
  "architecture": {
    "64bit": {
      "url": "https://ghproxy.com/https://github.com/Kyome22/RunCat365/releases/download/2.0/RunCat-x64.zip",
      "hash": "eac57dff96005068b5a150b261812ce8a8942d934ef2bd1022fecd8481cf7fb5"
    }
  },
  "shortcuts": [
    [
      "RunCat.exe",
      "RunCat"
    ]
  ],
  "suggest": {
    "dotnet core SDK": "dotnet-sdk"
  },
  "checkver": {
    "github": "https://github.com/Kyome22/RunCat365"
  },
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://ghproxy.com/https://github.com/Kyome22/RunCat365/releases/download/$version/RunCat-x64.zip"
      }
    }
  }
}

=== z-Fng/DEV-tools/bucket/elasticsearch_exporter.json
{
  "version": "1.6.0",
  "description": "A Prometheus exporter for Redis metrics.",
  "homepage": "https://github.com/prometheus-community/elasticsearch_exporter",
  "license": "Apache-2.0",
  "architecture": {
    "64bit": {
      "url": "https://ghproxy.com/https://github.com/prometheus-community/elasticsearch_exporter/releases/download/v1.6.0/elasticsearch_exporter-1.6.0.windows-amd64.tar.gz",
      "hash": "94ddd2910549e29cf0215eea70ed424c6b678d4d5e5f29fde52d572cb1bee3a4",
      "extract_dir": "elasticsearch_exporter-1.6.0.windows-amd64"
    },
    "32bit": {
      "url": "https://ghproxy.com/https://github.com/prometheus-community/elasticsearch_exporter/releases/download/v1.6.0/elasticsearch_exporter-1.6.0.windows-386.tar.gz",
      "hash": "6c18764cf3e57270479cdd36faf0e179ca9a2e27fa1f0cac147fa4445ec836fa",
      "extract_dir": "elasticsearch_exporter-1.6.0.windows-386"
    }
  },
  "bin": "elasticsearch_exporter.exe",
  "checkver": "github",
  "autoupdate": {
    "architecture": {
      "64bit": {
        "url": "https://ghproxy.com/https://github.com/prometheus-community/elasticsearch_exporter/releases/download/v$version/elasticsearch_exporter-$version.windows-amd64.tar.gz",
        "extract_dir": "elasticsearch_exporter-$version.windows-amd64"
      },
      "32bit": {
        "url": "https://ghproxy.com/https://github.com/prometheus-community/elasticsearch_exporter/releases/download/v$version/elasticsearch_exporter-$version.windows-386.tar.gz",
        "extract_dir": "elasticsearch_exporter-$version.windows-386"
      }
    },
    "hash": {
      "url": "$baseurl/sha256sums.txt"
    }
  }
}

=== z-Fng/DEV-tools/bucket/nhentai-cross.json
{
    "version": "0.0.9",
    "description": "A nhentai client",
    "homepage": "https://github.com/ComicSparks/nhentai-cross",
    "license": {
        "identifier": "MIT"
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/ComicSparks/nhentai-cross/releases/download/v0.0.9/nhentai-cross-v0.0.9-windows-x86_64.zip",
            "hash": "55c57eefa29f7d3b1047f9f9704255120021ea0cf8e2f33ba84d5b607db1d6bf"
        }
    },
    "shortcuts": [
        [
            "nhentai.exe",
            "nhentai"
        ]
    ],
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/ComicSparks/nhentai-cross/releases/download/v$version/nhentai-cross-v$version-windows-x86_64.zip"
            }
        }
    }
}

=== z-Fng/DEV-tools/bucket/tiddlydesktop-prerelease.json
{
    "homepage": "https://github.com/TiddlyWiki/TiddlyDesktop",
    "description": "A custom desktop browser for TiddlyWiki 5 and TiddlyWiki Classic, based on nw.js",
    "license": "Unknown",
    "version": "0.0.20",
    "architecture": {
        "64bit": {
            "url": "https://github.com/TiddlyWiki/TiddlyDesktop/releases/download/v0.0.20/tiddlydesktop-win64-v0.0.20.zip",
            "hash": "f43afb959a9111b84afe8e447075cd6f50c228f914af0e2f1b46485f6d5aba9c",
            "extract_dir": "TiddlyDesktop-win64-v0.0.20"
        },
        "32bit": {
            "url": "https://github.com/TiddlyWiki/TiddlyDesktop/releases/download/v0.0.20/tiddlydesktop-win32-v0.0.20.zip",
            "hash": "b0ddb918b36ddcffb9e6e48b0e79b4a1cfbcad0b3fd24043fee1cdb456e65832",
            "extract_dir": "TiddlyDesktop-win32-v0.0.20"
        }
    },
    "bin": [
        [
            "nw.exe",
            "tiddlydesktop"
        ]
    ],
    "shortcuts": [
        [
            "nw.exe",
            "TiddlyDesktop"
        ]
    ],
    "checkver": {
        "url": "https://api.github.com/repos/TiddlyWiki/TiddlyDesktop/tags",
        "jsonpath": "$..name",
        "regex": "v([\\d.]+(-prerelease\\.\\d+)?)"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/TiddlyWiki/TiddlyDesktop/releases/download/v$version/tiddlydesktop-win64-v$version.zip",
                "extract_dir": "TiddlyDesktop-win64-v$version"
            },
            "32bit": {
                "url": "https://github.com/TiddlyWiki/TiddlyDesktop/releases/download/v$version/tiddlydesktop-win32-v$version.zip",
                "extract_dir": "TiddlyDesktop-win32-v$version"
            }
        }
    }
}

=== z-Fng/DEV-tools/bucket/AutoDarkMode_dodorz.json
{
  "homepage": "https://github.com/AutoDarkMode/Windows-Auto-Night-Mode",
  "license": "GPL-3.0-or-later",
  "version": "10.4.1.1",
  "url": "https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/download/10.4.1.1/AutoDarkMode_10.4.1.1.zip",
  "hash": "9f56b01643d2bfe9a18e13e1792662b7d50708ab1ac6fedcf87378bbc8fe43b0",
  "bin": "AutoDarkMode.exe",
  "shortcuts": [
    [
      "AutoDarkMode.exe",
      "Windows 10 Auto Dark Mode"
    ]
  ],
  "persist": "overrides.json",
  "checkver": "github",
  "autoupdate": {
    "url": "https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/download/$version/AutoDarkMode_$version.zip",
    "hash": {
      "url": "https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/download/$version/AutoDarkModeX_$version.sha256"
    }
  }
}

=== z-Fng/DEV-tools/bucket/execti.json
{
  "##": "RunAs TrustedInstaller (same as root on unix)",
  "homepage": "https://winaero.com/blog/execti-run-programs-trustedinstaller/",
  "version": "1.0.0",
  "url": "https://github.com/rswch/scoop-app-mirror/raw/master/apps/ExecTI-1.0.0.7z",
  "hash": "c19d8164e58ac2f631826bee38e57dfc3de6a90cb747d001037b6062c2df3b85",
  "bin": "ExecTI.exe",
  "shortcuts": [
    [
      "ExecTI.exe",
      "ExecAsTrustedInstaller"
    ]
  ],
  "persist": [
    "ExecTI.ini"
  ]
}
